services:
  nginx:
    image: chainguard/nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway" # Adds the magic hostname
    depends_on:
      - kratos
      - game-backend
    networks:
      - intra-net
  game-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DBSTRING=${DBSTRING}
      - KRATOS_URL=${KRATOS_URL}
    depends_on:
      - game-db
    networks:
      - intra-net
      - game-net
  game-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - game_postgres_data:/var/lib/postgresql
    networks:
      - game-net
  kratos-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${KRATOS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${KRATOS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${KRATOS_POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - kratos_postgres_data:/var/lib/postgresql
    networks:
      - kratos-net
  kratos-migrate:
    image: oryd/kratos:v26.2.0
    restart: on-failure
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    environment:
      - DSN=${KRATOS_DSN}
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - kratos-net
    depends_on:
      - kratos-db
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v26.2.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    environment:
      - DSN=${KRATOS_DSN}
      - LOG_LEVEL=trace
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intra-net
      - kratos-net
volumes:
  game_postgres_data:
  kratos_postgres_data:
networks:
  intra-net:
  kratos-net:
  game-net:
